version: '3'

services:
  web:
    build: flask
    command: gunicorn -b 0.0.0.0:8000 app:app
    volumes:
      - .:/app
    environment:
      - DOMAIN_NAME=example.com

  nginx:
    build: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot-data:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    environment:
      - DOMAIN_NAME=example.com
